### ISSUE TITLE
Common homepage checks

### ISSUE THREAD

**Issue by BarryBotha** [passmarked/seo#4]
To test whether common homepage URL's are accessible with the same content being served as the naked domain (actual homepage) will help to determine whether the web server serves duplicate content on different URL's.

Some common ones include:
- index.php
- home.php
- default.php
- index.html
- home.html
- default.html
- index.aspx
- home.aspx
- default.aspx

**Comment by Johanndutoit** [comment]
Noted this would be great to have checked, expect a PR soon 👍

**Comment by Johanndutoit** [comment]
See PR #8 and let me know if you agree, will merge after a review and some testing on our environment. Thanks !

**Comment by Johanndutoit** [comment]
Just merged to develop, closing.
