### ISSUE TITLE
Check for trailing slashes

### ISSUE THREAD

**Issue by BarryBotha** [passmarked/seo#5]
There should be different content on URLs with and without slashes. Although this should be OK with search engines (don't leave it to chance) it is bad convention and could confuse users. URL's with a trailing slash typically denote a directory.

Read more: [https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html)

**Comment by Johanndutoit** [comment]
Noted, PR incoming 👍

**Comment by Johanndutoit** [comment]
Ask and ye shall receive, check out the PR for the rule over at #9. Would love some feedback as this is a interesting one.

**Comment by Johanndutoit** [comment]
Merged and going live after a few tests :)
