### ISSUE TITLE
check for valid sitemap.xml 

### ISSUE THREAD

**Issue by BarryBotha** [passmarked/seo#6]
Although we do not believe in the necessity of a sitemap.xml file we do believe that if you have one it should be valid. If /sitemap.xml returns 200 we should parse it to make sure its valid.

Read more: [http://www.sitemaps.org/protocol.html](http://www.sitemaps.org/protocol.html)

**Comment by Johanndutoit** [comment]
Ooooh that is interesting yes, would save a few servers some processing too if they are rendering the entire page instead of either a 404 or XML. PR incoming 👍

**Comment by Johanndutoit** [comment]
Storm-is-a-brewing - #10, feedback much appreciated :)

**Comment by Johanndutoit** [comment]
Merged and going live after some testing
